# Generated by Django 5.2.8 on 2025-11-14 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('times_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Utilisateur'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation')),
                ('recommended_flights', models.ManyToManyField(blank=True, to='catalog.flight')),
                ('recommended_hotels', models.ManyToManyField(blank=True, to='catalog.hotel')),
                ('recommended_packages', models.ManyToManyField(blank=True, to='catalog.tourpackage')),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_stars', models.IntegerField(blank=True, null=True)),
                ('preferred_destinations', models.JSONField(blank=True, default=list)),
                ('likes_wifi', models.BooleanField(default=True)),
                ('likes_pool', models.BooleanField(default=False)),
                ('likes_spa', models.BooleanField(default=False)),
                ('likes_restaurant', models.BooleanField(default=False)),
                ('search_history', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
            },
        ),
    ]
