# Generated by Django 5.2.8 on 2025-11-10 23:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='destinations/', verbose_name='Image')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Destination populaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code promo')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], max_length=20, verbose_name='Type de réduction')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur de la réduction')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('max_uses', models.IntegerField(blank=True, null=True, verbose_name='Utilisations maximales')),
                ('times_used', models.IntegerField(default=0, verbose_name='Fois utilisée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100, verbose_name='Compagnie aérienne')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Numéro de vol')),
                ('departure_time', models.DateTimeField(verbose_name='Heure de départ')),
                ('arrival_time', models.DateTimeField(verbose_name="Heure d'arrivée")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (TND)')),
                ('available_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sièges disponibles')),
                ('is_direct', models.BooleanField(default=True, verbose_name='Vol direct')),
                ('baggage_included', models.BooleanField(default=True, verbose_name='Bagage inclus')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='catalog.destination', verbose_name='Destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='catalog.destination', verbose_name='Origine')),
            ],
            options={
                'verbose_name': 'Vol',
                'verbose_name_plural': 'Vols',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('stars', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=3, verbose_name="Nombre d'étoiles")),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix par nuit (TND)')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='WiFi')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Piscine')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('has_restaurant', models.BooleanField(default=False, verbose_name='Restaurant')),
                ('has_spa', models.BooleanField(default=False, verbose_name='Spa')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('total_rooms', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de chambres')),
                ('image_main', models.ImageField(upload_to='hotels/', verbose_name='Image principale')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='catalog.destination', verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Hôtel',
                'verbose_name_plural': 'Hôtels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.hotel', verbose_name='Hôtel')),
            ],
            options={
                'verbose_name': "Image d'hôtel",
                'verbose_name_plural': "Images d'hôtels",
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du circuit')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (jours)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (TND)')),
                ('includes_hotel', models.BooleanField(default=True, verbose_name='Hôtel inclus')),
                ('includes_flight', models.BooleanField(default=True, verbose_name='Vol inclus')),
                ('includes_meals', models.BooleanField(default=False, verbose_name='Repas inclus')),
                ('includes_guide', models.BooleanField(default=False, verbose_name='Guide inclus')),
                ('itinerary', models.TextField(help_text='Décrivez le programme jour par jour', verbose_name='Itinéraire détaillé')),
                ('max_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre max de participants')),
                ('image', models.ImageField(upload_to='packages/', verbose_name='Image')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalog.destination', verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Circuit touristique',
                'verbose_name_plural': 'Circuits touristiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
