# Generated by Django 5.2.8 on 2025-11-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_favorite_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_destinations',
            field=models.JSONField(blank=True, default=list, verbose_name='Destinations favorites'),
        ),
    ]
